# Better tmux config

###########
# GENERAL #
###########

# Set prefix to Alt+a
unbind C-b
set -g prefix M-a

# enable mouse control
set -g mouse on

# increase scrollback buffer
set -g history-limit 50000

# fix Vim ESC delay
set -sg escape-time 0

# start windows and panes at 1 (instead of 0)
set -g base-index 1
setw -g pane-base-index 1

##############
# APPEARANCE #
##############

# start terminal with proper colors
set -g default-terminal "tmux-256color"
set -as terminal-features ",xterm-256color:RGB"

# status bar colors
set -g status-bg black
set -g status-fg white

# panes
set -g pane-border-style 'fg=#63686d'
set -g pane-active-border-style 'fg=#00e68a'

# window status
setw -g window-status-format ' #I:#W '
setw -g window-status-current-format '#[fg=#00e68a,bold] #I:#W '

# messages
set -g message-style 'fg=#000000 bg=#00b35a bold'

################
# KEY BINDINGS #
################

# split panes using \ and - (and keep current path)
bind \\ split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"
unbind '"'
unbind '%'

# reload config with 'r'
bind r source-file ~/.tmux.conf \; display "Config reloaded!"

# change panes with Alt+<arrow>
unbind Left
unbind Right
unbind Up
unbind Down
bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D

# Vim-style pane resizing
bind -r h resize-pane -L 5
bind -r l resize-pane -R 5
bind -r k resize-pane -U 5
bind -r j resize-pane -D 5
